TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'JohannesSteu.Neos.News': TRUE
    nodeTypes:
      groups:
        news:
          position: 180
          label: 'News'
    userInterface:
      translation:
        autoInclude:
          'JohannesSteu.Neos.News': ['NodeTypes/*']